// Send GET http request
GET http://localhost:5134/games

###
GET http://localhost:5134/games/3BEF4AD3-B5F0-4BAC-A341-042D2B5C2564

###
POST http://localhost:5134/games
Content-Type: application/json

{
    "name": "TEST GAME",
    "genreId": "EAB839B0-9695-45B0-956E-C7EACB486B23",
    "price": 99.99,
    "releaseDate": "1992-07-15",
    "description": "Test Description"
}

###
PUT http://localhost:5134/games/3BEF4AD3-B5F0-4BAC-A341-042D2B5C2564
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genreId": "EAB839B0-9695-45B0-956E-C7EACB486B23",
    "price": 19.99,
    "releaseDate": "1992-07-15",
    "description": "Street Fighter II Turbo is a high-speed arcade fighting game that refines the classic Street Fighter II experience with faster gameplay, new move sets, and enhanced competitive balance. Players choose from a roster of iconic fighters, each with unique abilities, to engage in intense one-on-one battles. Featuring improved mechanics, faster combat, and the introduction of Turbo mode, this edition delivers the ultimate test of skill and strategy for fighting game enthusiasts."
}

###
DELETE http://localhost:5134/games/a038186c-40a2-475f-8da8-6261d829a29c
###
GET http://localhost:5134/genres