// Send GET http request
GET http://localhost:5134/games?pageNumber=2

###
GET http://localhost:5134/games/8c1bcb2e-7a01-4ca8-bec5-0403818583ad

###
POST http://localhost:5134/games
Content-Type: application/json

{
    "name": "Tekken 8",
    "genreId": "eab839b0-9695-45b0-956e-c7eacb486b23",
    "price": 59.99,
    "releaseDate": "2024-01-26",
    "description": "Tekken 8 is a 2024 fighting game developed by Bandai Namco Studios and Arika and published by Bandai Namco Entertainment. It is the eighth main installment in the Tekken series and the first one to debut on home systems instead of arcades."
}

###
PUT http://localhost:5134/games/ab021e08-2edf-4000-918f-5538b8ed472b
Content-Type: application/json

{
    "name": "Final Fantasy XIV",
    "genreId": "68fdda7c-55c9-4274-8d7a-2d914997ce58",
    "price": 49.99,
    "releaseDate": "2010-09-30",
    "description": "Final Fantasy XIV is a massively multiplayer online role-playing game (MMORPG) set in the expansive world of Eorzea. Featuring an engaging storyline, deep character customization, and epic large-scale battles, players embark on adventures with friends, complete challenging raids, and explore breathtaking environments."
}

###
DELETE http://localhost:5134/games/59b706ad-8193-48d0-9c28-fac6bdf04fe5
###
GET http://localhost:5134/genres