// Send GET http request
GET http://localhost:5134/games

###
GET http://localhost:5134/games/4be391d0-0e09-4403-affc-c9d31851969f

###
POST http://localhost:5134/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5134/games/1769473c-3cfc-4328-88bd-791758f561d6
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}